name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    paths:
      - 'src/**'
      - 'package*.json'
      - 'tsconfig.json'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-linux:
    name: CI (Node 18 on ubuntu-latest)
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run all checks
      run: |
        npm run lint
        npm run format:check
        npm run compile

    - name: Package extension
      run: |
        npm install -g @vscode/vsce
        vsce package

    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: vscode-gitignore-guard-${{ github.sha }}
        path: '*.vsix'
        retention-days: 1

  ci-windows:
    name: CI (Node 18 on windows-latest)
    runs-on: windows-latest
    # Only run Windows builds on workflow_dispatch or tags
    if: ${{ (github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')) && !contains(github.event.head_commit.message, '[skip-ci]') }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run all checks
      run: |
        npm run lint
        npm run format:check
        npm run compile