name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run quality checks
      run: |
        npm run lint
        npm run format:check
        npm run compile

    - name: Package extension
      run: |
        npm install -g @vscode/vsce
        vsce package

    - name: Get release info
      id: release_info
      run: |
        VSIX_FILE=$(ls *.vsix)
        echo "VSIX_FILE=$VSIX_FILE" >> $GITHUB_OUTPUT
        
        # Use provided tag or extract from ref
        if [ "${{ github.event.inputs.tag }}" != "" ]; then
          TAG="${{ github.event.inputs.tag }}"
        else
          TAG="${{ github.ref_name }}"
        fi
        echo "TAG=$TAG" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ steps.release_info.outputs.VSIX_FILE }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ steps.release_info.outputs.TAG }}
        name: Gitignore Guard ${{ steps.release_info.outputs.TAG }}
        body: |
          ## What's Changed
          
          Check the [CHANGELOG](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md) for detailed changes.
          
          ## Installation
          
          ### From VS Code Marketplace
          1. Open VS Code
          2. Search for "Gitignore Guard" in Extensions
          3. Click Install
          
          ### From VSIX file
          1. Download the `.vsix` file below
          2. In VS Code: Extensions → "..." → "Install from VSIX..."
          3. Select the downloaded file
          
          ### Via command line
          ```bash
          code --install-extension ${{ steps.release_info.outputs.VSIX_FILE }}
          ```
        draft: false
        prerelease: ${{ contains(steps.release_info.outputs.TAG, 'beta') || contains(steps.release_info.outputs.TAG, 'alpha') }}
        generate_release_notes: true
